version: '3.8'
services:
  rr-discord-app:
    build: ./rocketrandy-bot/
    volumes:
      - ./rocketrandy-bot/:/usr/src/bot/
    container_name: rr-discord-bot
    env_file:
      - ./rocketrandy-bot/.env.compose
    networks:
      frontend:
  rr-postgres:
    image: postgres:13-alpine
    container_name: rr-postgres
    ports:
    - "5432:5432"
    volumes:
      - rr_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=rr_admin
      - POSTGRES_PASSWORD=rr_pass
      - POSTGRES_DB=rr_data
    networks:
      backend:
  rr-api:
    build: ./rocketrandy-api/
    container_name: rr-api
    volumes:
      - ./rocketrandy-api/:/usr/src/api/
    ports:
    - "5000:5000"
    env_file:
      - ./rocketrandy-api/app/.env.compose
    networks:
      frontend:
      backend:
volumes:
  rr_data:
networks:
  frontend:
  backend: