"""empty message

Revision ID: 2c3f3b029206
Revises: 2cf898a8b884
Create Date: 2021-04-27 16:17:58.912658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c3f3b029206"
down_revision = "2cf898a8b884"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "greetings", ["response"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "greetings", type_="unique")
    # ### end Alembic commands ###
