"""empty message

Revision ID: 2cf898a8b884
Revises: 5a6a966979d9
Create Date: 2021-04-27 14:15:23.032347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2cf898a8b884"
down_revision = "5a6a966979d9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
