"""empty message

Revision ID: 2d2ee5421334
Revises: 5ebccb1a0adc
Create Date: 2021-04-27 19:30:58.072776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2ee5421334'
down_revision = '5ebccb1a0adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
