"""remove user greeting relationship

Revision ID: 3c54ba56e940
Revises: 4801f2bf7c6e
Create Date: 2021-04-27 11:36:37.744733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3c54ba56e940"
down_revision = "4801f2bf7c6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("greetings_added_by_fkey", "greetings", type_="foreignkey")
    op.drop_column("greetings", "added_by")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "greetings",
        sa.Column("added_by", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "greetings_added_by_fkey", "greetings", "users", ["added_by"], ["id"]
    )
    # ### end Alembic commands ###
