"""add basic greetings

Revision ID: 4801f2bf7c6e
Revises: 2b2cd7544762
Create Date: 2021-04-26 16:40:02.355349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4801f2bf7c6e"
down_revision = "2b2cd7544762"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "greetings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("response", sa.String(), nullable=True),
        sa.Column("added_by", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("users", sa.Column("date_first_seen", sa.Date(), nullable=True))
    op.drop_column("users", "discord_member_id")
    op.drop_column("users", "date_joined")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("date_joined", sa.DATE(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("discord_member_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.drop_column("users", "date_first_seen")
    op.drop_table("greetings")
    # ### end Alembic commands ###
