"""test new model structure

Revision ID: 49a7ffc7515b
Revises: 3c54ba56e940
Create Date: 2021-04-27 12:48:33.756304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a7ffc7515b'
down_revision = '3c54ba56e940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('greetings', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('greetings', 'number')
    # ### end Alembic commands ###
