"""empty message

Revision ID: 5524126ea8fe
Revises: 9dc52c6a7cbb
Create Date: 2021-04-27 19:25:32.551158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5524126ea8fe'
down_revision = '9dc52c6a7cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
