"""empty message

Revision ID: 5a6a966979d9
Revises: d72fd7d0d386
Create Date: 2021-04-27 14:06:40.754344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5a6a966979d9"
down_revision = "d72fd7d0d386"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("greetings", sa.Column("added_by", sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, "greetings", "users", ["added_by"], ["member_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "greetings", type_="foreignkey")
    op.drop_column("greetings", "added_by")
    # ### end Alembic commands ###
