"""empty message

Revision ID: 5ebccb1a0adc
Revises: 5524126ea8fe
Create Date: 2021-04-27 19:28:52.717637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ebccb1a0adc'
down_revision = '5524126ea8fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
