"""empty message

Revision ID: c72184919554
Revises: f66bc0830937
Create Date: 2021-04-27 16:56:13.604294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c72184919554"
down_revision = "f66bc0830937"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connectedaccounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "platform", sa.Enum("steam", "epic", name="platforms"), nullable=True
        ),
        sa.Column("platform_username", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["users.member_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("connectedaccounts")
    # ### end Alembic commands ###
