"""empty message

Revision ID: d72fd7d0d386
Revises: 
Create Date: 2021-04-27 14:04:59.947150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d72fd7d0d386"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "greetings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("response", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("member_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("date_first_seen", sa.Date(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("member_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("greetings")
    # ### end Alembic commands ###
