"""remove test

Revision ID: ef489864759c
Revises: 49a7ffc7515b
Create Date: 2021-04-27 12:55:24.222978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef489864759c'
down_revision = '49a7ffc7515b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('greetings', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('greetings', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
