"""empty message

Revision ID: f66bc0830937
Revises: 2c3f3b029206
Create Date: 2021-04-27 16:19:47.553123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f66bc0830937"
down_revision = "2c3f3b029206"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rlthreesranks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.BigInteger(), nullable=True),
        sa.Column("season", sa.Integer(), nullable=True),
        sa.Column("mmr", sa.Integer(), nullable=True),
        sa.Column("date_collected", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["users.member_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rlthreesranks")
    # ### end Alembic commands ###
